# Generated by Eden
import asyncio
import sys
import logging
from logging.config import fileConfig
from sqlalchemy import pool, text
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config
from alembic import context

# 1. Load Alembic config
config = context.config

# 2. Setup logging
logger = logging.getLogger("alembic.env")
if config.config_file_name is not None:
    fileConfig(config.config_file_name)
else:
    logging.basicConfig(level=logging.INFO)

logger.info(f"Using database URL: {config.get_main_option('sqlalchemy.url')}")

# 3. Load Eden config and set database URL if not already provided
if not config.get_main_option("sqlalchemy.url"):
    from eden.config import get_config
    eden_config = get_config()
    config.set_main_option("sqlalchemy.url", eden_config.get_database_url())

# 4. Import Eden models to populate metadata
from eden.db import Model, discover_models

# Dinamically discover all project models so Alembic recognizes them
discover_models()

target_metadata = Model.metadata

def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode."""
    url = config.get_main_option("sqlalchemy.url")
    
    tenant_schema = config.get_main_option("tenant_schema")
    # Determine version table based on whether we're in a tenant context
    version_table = config.get_main_option("version_table") or ("alembic_version_tenant" if tenant_schema else "alembic_version")

    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        version_table=version_table,
        include_object=config.attributes.get("include_object"),
        render_as_batch=True,
    )

    with context.begin_transaction():
        context.run_migrations()

def do_run_migrations(connection: Connection) -> None:
    tenant_schema = config.get_main_option("tenant_schema")
    version_table = config.get_main_option("version_table") or ("alembic_version_tenant" if tenant_schema else "alembic_version")

    # For tenant migrations, ensure we target the right schema
    # We set search_path so that all tables created (without explicit schema)
    # in the migration revisions end up in the tenant's schema.
    
    context.configure(
        connection=connection, 
        target_metadata=target_metadata,
        version_table=version_table,
        include_object=config.attributes.get("include_object"),
        render_as_batch=True,
    )

    with context.begin_transaction():
        if tenant_schema and connection.dialect.name == "postgresql":
            # Direct execution in the transaction block
            logger.info(f"Migrations: Setting search_path to {tenant_schema}")
            connection.execute(text(f'SET LOCAL search_path TO "{tenant_schema}"'))
        
        current_db_schema = connection.execute(text("SELECT current_schema()")).scalar()
        logger.info(f"Migrations: Context: schema={tenant_schema}, version_table={version_table}, actual_current_schema={current_db_schema}")

        context.run_migrations()
    
    # Verify tables actually exist
    tables = connection.execute(text("""
        SELECT schemaname, tablename 
        FROM pg_tables 
        WHERE schemaname NOT IN ('pg_catalog', 'information_schema')
    """)).fetchall()
    logger.info(f"Verification inside env.py: Tables = {[(t[0], t[1]) for t in tables]}")

async def run_migrations_online() -> None:
    """Run migrations in 'online' mode."""
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
        await connection.commit()
        logger.info("Migrations: online migration committed.")

    await connectable.dispose()

if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
