# Generated by Eden
import asyncio
import sys
from logging.config import fileConfig
from sqlalchemy import pool, text
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config
from alembic import context

# 1. Load Alembic config
config = context.config

# 2. Setup logging
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# 3. Load Eden config and set database URL if not already provided
if not config.get_main_option("sqlalchemy.url"):
    from eden.config import get_config
    eden_config = get_config()
    config.set_main_option("sqlalchemy.url", eden_config.get_database_url())

# 4. Import Eden models to populate metadata
from eden.db import Model, discover_models

# Dinamically discover all project models so Alembic recognizes them
discover_models()

target_metadata = Model.metadata

def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode."""
    url = config.get_main_option("sqlalchemy.url")
    
    tenant_schema = config.get_main_option("tenant_schema")
    # Determine version table based on whether we're in a tenant context
    version_table = config.get_main_option("version_table") or ("alembic_version_tenant" if tenant_schema else "alembic_version")

    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        version_table=version_table,
        include_object=config.attributes.get("include_object"),
        render_as_batch=True,
    )

    with context.begin_transaction():
        context.run_migrations()

def do_run_migrations(connection: Connection) -> None:
    tenant_schema = config.get_main_option("tenant_schema")
    version_table = config.get_main_option("version_table") or ("alembic_version_tenant" if tenant_schema else "alembic_version")

    # If schema is specified, it might need to be set in the connection
    if tenant_schema and connection.dialect.name == "postgresql":
        connection.execute(text(f'SET search_path TO "{tenant_schema}"'))

    context.configure(
        connection=connection, 
        target_metadata=target_metadata,
        version_table=version_table,
        include_object=config.attributes.get("include_object"),
        render_as_batch=True,
    )
    with context.begin_transaction():
        context.run_migrations()

async def run_migrations_online() -> None:
    """Run migrations in 'online' mode."""
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()

if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
