# Generated by Eden
import asyncio
from logging.config import fileConfig
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config
from alembic import context

# 1. Load Alembic config
config = context.config

# 2. Setup logging
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# 3. Load Eden config and set database URL
from eden.config import get_config
eden_config = get_config()
config.set_main_option("sqlalchemy.url", eden_config.get_database_url())

# 4. Import Eden models to populate metadata
from eden.db import Model
# Ensure all models are imported here or via a central registry
import eden.auth.models
import eden.tenancy.models
import eden.admin.models
target_metadata = Model.metadata

def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()

def do_run_migrations(connection: Connection) -> None:
    context.configure(connection=connection, target_metadata=target_metadata)
    with context.begin_transaction():
        context.run_migrations()

async def run_migrations_online() -> None:
    """Run migrations in 'online' mode."""
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()

if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
