"""
Eden — Database ORM Package

Provides the data layer: Model base class, Field helpers,
Database session management, and Alembic migration integration.
"""

from eden.db.base import Model
from eden.db.fields import (
    BoolField,
    DateTimeField,
    FloatField,
    ForeignKeyField,
    IntField,
    ManyToManyField,
    Relationship,
    Reference,
    StringField,
    TextField,
    UUIDField,
    FileField,
    f,
)
from sqlalchemy import (
    select,
    update,
    delete,
    insert,
    func,
    text,
    inspect,
    event,
    MetaData,
    Table,
    Column,
    ForeignKey,
    Index,
    UniqueConstraint,
    CheckConstraint,
    PrimaryKeyConstraint,
    ForeignKeyConstraint,
    Sequence,
    Identity,
    Computed,
    DefaultClause,
    String,
    Integer,
    SmallInteger,
    BigInteger,
    Numeric,
    Float,
    Boolean,
    DateTime,
    Date,
    Time,
    Interval,
    Uuid,
    JSON,
    Enum,
    ARRAY,
    Unicode,
    UnicodeText,
    LargeBinary,
    TypeDecorator,
    and_,
    or_,
    not_,
    desc,
    asc,
    union,
    union_all,
    exists,
    distinct,
    between,
    case,
    cast,
    extract,
    null,
    true,
    false,
)
from sqlalchemy.orm import (
    Mapped,
    mapped_column,
    relationship,
    selectinload,
    joinedload,
    subqueryload,
    contains_eager,
    aliased,
    column_property,
    validates,
)
from sqlalchemy.ext.asyncio import AsyncSession

from eden.db.aggregates import Sum, Avg, Count, Min, Max
from eden.db.lookups import F, Q
from eden.db.mixins import SoftDeleteMixin
from eden.db.pagination import Page
from eden.db.query import QuerySet
from eden.db.session import Database, get_db, init_db
from eden.context import request, user

__all__ = [
    "Model",
    "Database",
    "get_db",
    "init_db",
    "Q",
    "F",
    "f",
    "Sum",
    "Avg",
    "Count",
    "Min",
    "Max",
    "Page",
    "SoftDeleteMixin",
    "StringField",
    "IntField",
    "TextField",
    "BoolField",
    "FloatField",
    "DateTimeField",
    "UUIDField",
    "ForeignKeyField",
    "Relationship",
    "Reference",
    "ManyToManyField",
    "FileField",
    "QuerySet",
    "Mapped",
    "mapped_column",
    "relationship",
    "selectinload",
    "joinedload",
    "select",
    "update",
    "delete",
    "insert",
    "func",
    "text",
    "inspect",
    "event",
    "MetaData",
    "Table",
    "Column",
    "ForeignKey",
    "Index",
    "UniqueConstraint",
    "CheckConstraint",
    "PrimaryKeyConstraint",
    "ForeignKeyConstraint",
    "Sequence",
    "Identity",
    "Computed",
    "DefaultClause",
    "AsyncSession",
    "String",
    "Integer",
    "SmallInteger",
    "BigInteger",
    "Numeric",
    "Float",
    "Boolean",
    "DateTime",
    "Date",
    "Time",
    "Interval",
    "Uuid",
    "JSON",
    "Enum",
    "ARRAY",
    "Unicode",
    "UnicodeText",
    "LargeBinary",
    "TypeDecorator",
    "and_",
    "or_",
    "not_",
    "desc",
    "asc",
    "union",
    "union_all",
    "exists",
    "distinct",
    "between",
    "case",
    "cast",
    "extract",
    "null",
    "true",
    "false",
    "subqueryload",
    "contains_eager",
    "aliased",
    "column_property",
    "validates",
    "request",
    "user",
]
