import os
import logging
from typing import Any, Optional
from alembic import command
from alembic.config import Config

logger = logging.getLogger("eden.migrations")


class MigrationManager:
    """
    MigrationManager: Eden's database migration engine.
    Handles schema evolution using Alembic under the hood.
    
    This manager automates the creation of alembic.ini and env.py
    tailored for Eden's metadata and configuration.
    """

    def __init__(self, database_url: str):
        self.database_url = database_url
        self.config = self._get_alembic_config()

    def _get_alembic_config(self) -> Config:
        """Initialize Alembic configuration."""
        # Check for alembic.ini in current directory or app root
        ini_path = "alembic.ini"
        if not os.path.exists(ini_path):
            # Fallback to a default location or error
            logger.warning("alembic.ini not found. Using default config.")

        cfg = Config(ini_path)
        cfg.set_main_option("sqlalchemy.url", self.database_url)
        # Ensure script_location is set (usually 'migrations')
        if not cfg.get_main_option("script_location"):
            cfg.set_main_option("script_location", "migrations")
        return cfg

    async def init(self) -> None:
        """Initialize migration directory and configuration files."""
        logger.info("Migrations: Initializing environment...")
        script_location = self.config.get_main_option("script_location") or "migrations"
        
        if not os.path.exists(script_location):
            os.makedirs(script_location, exist_ok=True)
            logger.info(f"Migrations: Created directory '{script_location}'.")

        # 1. Create alembic.ini if not present
        if not os.path.exists("alembic.ini"):
            self._write_alembic_ini()
            logger.info("Migrations: Created alembic.ini")

        # 2. Create env.py inside migrations directory
        env_path = os.path.join(script_location, "env.py")
        if not os.path.exists(env_path):
            self._write_env_py(env_path)
            logger.info(f"Migrations: Created {env_path}")
        
        # 3. Create script.py.mako if not present
        mako_path = os.path.join(script_location, "script.py.mako")
        if not os.path.exists(mako_path):
            self._write_mako(mako_path)
            logger.info(f"Migrations: Created {mako_path}")

    def _write_alembic_ini(self):
        with open("alembic.ini", "w") as f:
            f.write("""# Generated by Eden
[alembic]
script_location = migrations
file_template = %%(rev)s_%%(slug)s
prepend_sys_path = .

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
""")

    def _write_env_py(self, path: str):
        with open(path, "w") as f:
            f.write("""# Generated by Eden
import asyncio
from logging.config import fileConfig
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config
from alembic import context

# 1. Load Alembic config
config = context.config

# 2. Setup logging
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# 3. Import Eden models to populate metadata
from eden.db import Model
# Ensure all models are imported here or via a central registry
target_metadata = Model.metadata

def run_migrations_offline() -> None:
    \"\"\"Run migrations in 'offline' mode.\"\"\"
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()

def do_run_migrations(connection: Connection) -> None:
    context.configure(connection=connection, target_metadata=target_metadata)
    with context.begin_transaction():
        context.run_migrations()

async def run_migrations_online() -> None:
    \"\"\"Run migrations in 'online' mode.\"\"\"
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()

if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
""")

    def _write_mako(self, path: str):
         with open(path, "w") as f:
            f.write("""\"\"\"${message}

Revision ID: ${up_revision}
Revises: ${down_revision}
Create Date: ${create_date}

\"\"\"
from alembic import op
import sqlalchemy as sa
${imports if imports else ""}

# revision identifiers, used by Alembic.
revision = ${repr(up_revision)}
down_revision = ${repr(down_revision)}
branch_labels = ${repr(branch_labels)}
depends_on = ${repr(depends_on)}


def upgrade() -> None:
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    ${downgrades if downgrades else "pass"}
""")

    async def generate(self, message: str, tenant_isolated: bool = False) -> None:
        """
        Detect schema changes and generate a new migration file.
        
        If tenant_isolated=True, it identifies changes in models marked with __eden_tenant_isolated__=True.
        """
        label = "Tenant" if tenant_isolated else "Shared"
        logger.info(f"Migrations: Generating {label} revision — '{message}'")
        
        # Configure the environment with isolation context
        opts = {
            "autogenerate": True,
            "version_table": "alembic_version_tenant" if tenant_isolated else "alembic_version",
            # This will be picked up by the env.py to filter metadata
            "include_object": self._make_include_object(tenant_isolated)
        }
        
        try:
            command.revision(self.config, message=message, **opts)
            logger.info(f"Migrations: {label} revision successfully generated.")
        except Exception as e:
            logger.error(f"Migration Error: {e}")
            raise

    async def migrate(self, revision: str = "head", schema: Optional[str] = None) -> None:
        """
        Apply pending migrations to the database.
        
        If schema is provided, it applies migrations specifically to that tenant schema.
        """
        target = f"schema '{schema}'" if schema else "default schema"
        logger.info(f"Migrations: Applying evolutions to {revision} on {target}...")
        
        config = self._get_alembic_config()
        if schema:
            # Tell Alembic to use a specific schema and target the tenant-specific version table
            config.set_main_option("tenant_schema", schema)
        
        try:
            command.upgrade(config, revision)
            logger.info(f"Migrations: {target} is now up-to-date.")
        except Exception as e:
            logger.error(f"Migration Error: {e}")
            raise

    def _make_include_object(self, tenant_isolated: bool):
        """Returns a filter function for Alembic auto-generation."""
        def include_object(obj, name, type_, reflected, compare_to):
            if type_ == "table":
                # Get the model associated with this table
                # NOTE: This assumes models are already loaded in metadata
                from eden.db import Model
                model = None
                for mapper in Model.registry.mappers:
                    if mapper.persist_selectable.name == name:
                        model = mapper.class_
                        break
                
                if model:
                    is_isolated = getattr(model, "__eden_tenant_isolated__", False)
                    return is_isolated == tenant_isolated
                
                # If no model found, default to shared if not explicitly isolation-requested
                return not tenant_isolated
            return True
        return include_object

    async def check(self) -> dict[str, str]:
        """
        Check for schema drift across all tenants.
        Returns a dictionary mapping schema names to their drift status (or "ok").
        """
        from alembic.script import ScriptDirectory
        from sqlalchemy import text, select
        from eden.db import Model
        from eden.tenancy.models import Tenant

        logger.info("Migrations: Checking for schema drift...")
        script = ScriptDirectory.from_config(self.config)
        head_revision = script.get_current_head()
        
        results = {}

        # 1. Check shared schema
        async with Model._get_db().session() as sess:
            res = await sess.execute(text("SELECT version_num FROM alembic_version LIMIT 1"))
            shared_version = res.scalar()
            results["shared"] = "ok" if shared_version == head_revision else f"drifted (expected {head_revision}, got {shared_version})"

            # 2. Get all tenants
            # Note: We use Model.query because Tenant is an EdenModel
            tenants = await sess.execute(select(Tenant))
            tenant_list = tenants.scalars().all()

            for tenant in tenant_list:
                schema = tenant.schema_name
                try:
                    # Check tenant version table
                    version_sql = text(f'SELECT version_num FROM "{schema}".alembic_version_tenant LIMIT 1')
                    res = await sess.execute(version_sql)
                    tenant_version = res.scalar()
                    
                    if tenant_version == head_revision:
                        results[schema] = "ok"
                    else:
                        results[schema] = f"drifted (expected {head_revision}, got {tenant_version})"
                except Exception as e:
                    results[schema] = f"error: {str(e)}"

        return results

    async def downgrade(self, revision: str) -> None:
        """Revert to a previous migration."""
        logger.info(f"Migrations: Reverting to {revision}...")
        try:
            command.downgrade(self.config, revision)
            logger.info("Migrations: Schema reverted.")
        except Exception as e:
            logger.error(f"Migration Error: {e}")
            raise

    def history(self) -> None:
        """Show migration history."""
        command.history(self.config)


# ── Functional Interface ──────────────────────────────────────────────────

def init_migrations(db_url: str):
    import asyncio
    manager = MigrationManager(db_url)
    asyncio.run(manager.init())


def create_migration(message: str, db_url: str):
    import asyncio
    manager = MigrationManager(db_url)
    asyncio.run(manager.generate(message))


def run_upgrade(revision: str, db_url: str):
    import asyncio
    manager = MigrationManager(db_url)
    asyncio.run(manager.migrate(revision))


def run_downgrade(revision: str, db_url: str):
    import asyncio
    manager = MigrationManager(db_url)
    asyncio.run(manager.downgrade(revision))


def show_history(db_url: str):
    manager = MigrationManager(db_url)
    manager.history()


def run_check(db_url: str) -> dict[str, str]:
    import asyncio
    manager = MigrationManager(db_url)
    return asyncio.run(manager.check())
