import asyncio
import logging
import os
from typing import Any

from alembic import command
from alembic.config import Config

logger = logging.getLogger("eden.migrations")


class MigrationError(Exception):
    """Base exception for all Eden migration operations."""
    pass


class MigrationManager:
    """
    MigrationManager: Eden's database migration engine.
    Handles schema evolution using Alembic under the hood.
    
    This manager automates the creation of alembic.ini and env.py
    tailored for Eden's metadata and configuration.
    """

    def __init__(self, database_url: str | None = None):
        self.database_url = database_url
        self.config = self._get_alembic_config()

    def _get_alembic_config(self) -> Config:
        """Initialize Alembic configuration."""
        # Check for alembic.ini in current directory or app root
        ini_path = "alembic.ini"
        if not os.path.exists(ini_path):
            # Fallback to a default location or error
            logger.warning("alembic.ini not found. Using default config.")

        cfg = Config(ini_path)

        # If no URL provided, get from Eden config
        url = self.database_url
        if not url:
            from eden.config import get_config
            url = get_config().get_database_url()

        cfg.set_main_option("sqlalchemy.url", url)
        # Ensure script_location is set (usually 'migrations')
        if not cfg.get_main_option("script_location"):
            cfg.set_main_option("script_location", "migrations")
        return cfg

    async def init(self) -> None:
        """Initialize migration directory and configuration files."""
        logger.info("Migrations: Initializing environment...")
        script_location = self.config.get_main_option("script_location") or "migrations"

        if not os.path.exists(script_location):
            os.makedirs(script_location, exist_ok=True)
            logger.info(f"Migrations: Created directory '{script_location}'.")

        # 1. Create alembic.ini if not present
        if not os.path.exists("alembic.ini"):
            self._write_alembic_ini()
            logger.info("Migrations: Created alembic.ini")

        # 2. Create env.py inside migrations directory
        env_path = os.path.join(script_location, "env.py")
        if not os.path.exists(env_path):
            self._write_env_py(env_path)
            logger.info(f"Migrations: Created {env_path}")

        # 3. Create script.py.mako if not present
        mako_path = os.path.join(script_location, "script.py.mako")
        if not os.path.exists(mako_path):
            self._write_mako(mako_path)
            logger.info(f"Migrations: Created {mako_path}")

    def _write_alembic_ini(self):
        with open("alembic.ini", "w") as f:
            f.write("""# Generated by Eden
[alembic]
script_location = migrations
file_template = %%(rev)s_%%(slug)s
prepend_sys_path = .

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
""")

    def _write_env_py(self, path: str):
        with open(path, "w") as f:
            f.write("""# Generated by Eden
import asyncio
import sys
from logging.config import fileConfig
from sqlalchemy import pool, text
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config
from alembic import context

# 1. Load Alembic config
config = context.config

# 2. Setup logging
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# 3. Load Eden config and set database URL if not already provided
if not config.get_main_option("sqlalchemy.url"):
    from eden.config import get_config
    eden_config = get_config()
    config.set_main_option("sqlalchemy.url", eden_config.get_database_url())

# 4. Import Eden models to populate metadata
from eden.db import Model, discover_models

# Dinamically discover all project models so Alembic recognizes them
discover_models()

target_metadata = Model.metadata

def run_migrations_offline() -> None:
    \"\"\"Run migrations in 'offline' mode.\"\"\"
    url = config.get_main_option("sqlalchemy.url")
    
    tenant_schema = config.get_main_option("tenant_schema")
    # Determine version table based on whether we're in a tenant context
    version_table = config.get_main_option("version_table") or ("alembic_version_tenant" if tenant_schema else "alembic_version")

    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        version_table=version_table,
        include_object=config.attributes.get("include_object"),
        render_as_batch=True,
    )

    with context.begin_transaction():
        context.run_migrations()

def do_run_migrations(connection: Connection) -> None:
    tenant_schema = config.get_main_option("tenant_schema")
    version_table = config.get_main_option("version_table") or ("alembic_version_tenant" if tenant_schema else "alembic_version")

    # If schema is specified, it might need to be set in the connection
    if tenant_schema and connection.dialect.name == "postgresql":
        connection.execute(text(f'SET search_path TO "{tenant_schema}"'))

    context.configure(
        connection=connection, 
        target_metadata=target_metadata,
        version_table=version_table,
        include_object=config.attributes.get("include_object"),
        render_as_batch=True,
    )
    with context.begin_transaction():
        context.run_migrations()

async def run_migrations_online() -> None:
    \"\"\"Run migrations in 'online' mode.\"\"\"
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()

if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
""")

    def _write_mako(self, path: str) -> None:
        with open(path, "w") as f:
            f.write("""\"\"\"${message}

Revision ID: ${up_revision}
Revises: ${down_revision}
Create Date: ${create_date}

\"\"\"
from alembic import op
import sqlalchemy as sa
${imports if imports else ""}

# revision identifiers, used by Alembic.
revision = ${repr(up_revision)}
down_revision = ${repr(down_revision)}
branch_labels = ${repr(branch_labels)}
depends_on = ${repr(depends_on)}
__eden_tenant_isolated__ = ${context.get("tenant_isolated", config.attributes.get("tenant_isolated", False))}


def upgrade() -> None:
    from alembic import context
    is_tenant_context = context.config.get_main_option("tenant_schema") is not None
    if is_tenant_context != __eden_tenant_isolated__:
        # Skip this migration if the context doesn't match the migration type
        return

    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    from alembic import context
    is_tenant_context = context.config.get_main_option("tenant_schema") is not None
    if is_tenant_context != __eden_tenant_isolated__:
        return

    ${downgrades if downgrades else "pass"}


""")

    async def upgrade(self, revision: str = "head") -> None:
        """Apply migrations up to the specified revision."""
        try:
            await asyncio.to_thread(command.upgrade, self.config, revision)
            logger.info("Migrations: upgraded to %s", revision)
        except Exception as exc:
            logger.exception("Migration upgrade failed")
            raise MigrationError("Migration upgrade failed") from exc

    async def downgrade(self, revision: str = "-1", schema: str | None = None) -> None:
        """Revert migrations down to the specified revision."""
        target = f"schema '{schema}'" if schema else "default schema"
        logger.info("Migrations: Reverting to %s on %s...", revision, target)

        config = self._get_alembic_config()
        if schema:
            config.set_main_option("tenant_schema", schema)

        try:
            await asyncio.to_thread(command.downgrade, config, revision)
            logger.info("Migrations: %s reverted to %s.", target, revision)
        except Exception as exc:
            logger.exception("Migration downgrade failed")
            raise MigrationError("Migration downgrade failed") from exc

    async def current(self) -> str:
        """Get the current database migration revision."""
        try:
            current_revision = await asyncio.to_thread(command.current, self.config, verbose=False)
            return current_revision or ""
        except Exception as exc:
            logger.exception("Unable to get current migration revision")
            raise MigrationError("Unable to get current migration revision") from exc

    async def stamp(self, revision: str = "head", schema: str | None = None) -> None:
        """Stamp the database with a specific revision without running migrations."""
        target = f"schema '{schema}'" if schema else "default schema"
        logger.info("Migrations: Stamping %s with %s...", target, revision)
        config = self._get_alembic_config()
        if schema:
            config.set_main_option("tenant_schema", schema)

        logger.debug("Migrations: Database URL for stamp: %s", config.get_main_option("sqlalchemy.url"))

        try:
            await asyncio.to_thread(command.stamp, config, revision)
            logger.info("Migrations: %s stamped.", target)
        except Exception as exc:
            logger.exception("Migration stamp failed")
            raise MigrationError("Migration stamp failed") from exc

    async def generate(self, message: str, tenant_isolated: bool = False) -> None:
        """
        Detect schema changes and generate a new migration file.
        
        If tenant_isolated=True, it identifies changes in models marked with __eden_tenant_isolated__=True.
        """
        script_location = self.config.get_main_option("script_location") or "migrations"
        if not os.path.exists(script_location):
            raise FileNotFoundError(f"Migrations directory '{script_location}' not found. Run 'eden db init' first.")

        label = "Tenant" if tenant_isolated else "Shared"
        logger.info(f"Migrations: Generating {label} revision — '{message}'")

        # Pass options via config attributes for env.py to pick up
        self.config.attributes["include_object"] = self._make_include_object(tenant_isolated)
        # Pass tenant_isolated via attributes for mako to pick up as a fallback
        self.config.attributes["tenant_isolated"] = tenant_isolated
        
        if tenant_isolated:
            self.config.set_main_option("version_table", "alembic_version_tenant")

        def process_revision_directives(context, revision, directives):
            """Hook to inject custom variables into the mako template context."""
            for script in directives:
                # Ensure template_args exist and set tenant_isolated
                if not hasattr(script, "template_args"):
                    script.template_args = {}
                # The template uses ${tenant_isolated}
                script.template_args["tenant_isolated"] = tenant_isolated

        try:
            # Pass custom data via process_revision_directives instead of direct keyword arguments
            await asyncio.to_thread(
                command.revision, 
                self.config, 
                message=message, 
                autogenerate=True, 
                process_revision_directives=process_revision_directives
            )
            logger.info(f"Migrations: {label} revision successfully generated.")
        except Exception as e:
            logger.error(f"Migration Error: {e}")
            raise MigrationError(f"Failed to generate migration: {e}")

    async def migrate(self, revision: str = "head", schema: str | None = None) -> None:
        """
        Apply pending migrations to the database.
        
        If schema is provided, it applies migrations specifically to that tenant schema.
        """
        target = f"schema '{schema}'" if schema else "default schema"
        logger.info(f"Migrations: Applying evolutions to {revision} on {target}...")

        config = self._get_alembic_config()
        if schema:
            # Tell Alembic to use a specific schema and target the tenant-specific version table
            config.set_main_option("tenant_schema", schema)

        try:
            await asyncio.to_thread(command.upgrade, config, revision)
            logger.info(f"Migrations: {target} is now up-to-date.")
        except Exception as e:
            logger.error(f"Migration Error: {e}")
            raise MigrationError(f"Failed to apply migrations: {e}")

    def _make_include_object(self, tenant_isolated: bool):
        """Returns a filter function for Alembic auto-generation."""
        def include_object(obj, name, type_, reflected, compare_to):
            if type_ == "table":
                # Get the model associated with this table
                # NOTE: This assumes models are already loaded in metadata
                from eden.db import Model
                model = None
                for mapper in Model.registry.mappers:
                    if mapper.persist_selectable.name == name:
                        model = mapper.class_
                        break

                if model:
                    is_isolated = getattr(model, "__eden_tenant_isolated__", False)
                    return is_isolated == tenant_isolated

                # If no model found, default to shared if not explicitly isolation-requested
                return not tenant_isolated
            return True
        return include_object

    async def check(self) -> dict[str, str]:
        """
        Check for schema drift across all tenants.
        Returns a dictionary mapping schema names to their drift status (or "ok").
        """
        from alembic.script import ScriptDirectory
        from sqlalchemy import select, text
        from sqlalchemy.ext.asyncio import create_async_engine
        from sqlalchemy.pool import NullPool

        from eden.tenancy.models import Tenant

        logger.info("Migrations: Checking for schema drift...")
        script = ScriptDirectory.from_config(self.config)
        head_revision = script.get_current_head()

        results = {}

        # Determine URL
        url_from_config = self.config.get_main_option("sqlalchemy.url")
        if url_from_config:
            url = url_from_config
        else:
            from eden.config import get_db_url
            url = self.database_url or get_db_url()

        engine = create_async_engine(url, poolclass=NullPool)

        try:
            # 1. Check shared schema
            async with engine.connect() as conn:
                try:
                    res = await conn.execute(text("SELECT version_num FROM alembic_version LIMIT 1"))
                    shared_version = res.scalar()
                    results["shared"] = "ok" if shared_version == head_revision else f"drifted (expected {head_revision}, got {shared_version})"
                except Exception as e:
                    results["shared"] = f"error: {str(e)}"

                # 2. Get all tenants directly using sqlalchemy without relying on ORM bindings
                try:
                    tenants_res = await conn.execute(select(Tenant))
                    for tenant in tenants_res.scalars().all():
                        schema = tenant.schema_name
                        if not schema:
                            continue
                        try:
                            # Check tenant version table
                            version_sql = text(f'SELECT version_num FROM "{schema}".alembic_version_tenant LIMIT 1')
                            res = await conn.execute(version_sql)
                            tenant_version = res.scalar()

                            if tenant_version == head_revision:
                                results[schema] = "ok"
                            else:
                                results[schema] = f"drifted (expected {head_revision}, got {tenant_version})"
                        except Exception as e:
                            # Handle case where the tenant schema or version table doesn't exist yet
                            if "does not exist" in str(e).lower() or "undefined_table" in str(e).lower():
                                results[schema] = "unprovisioned"
                            else:
                                results[schema] = f"error: {str(e)}"
                except Exception as e:
                    logger.warning(f"Failed to fetch tenants for drift check: {e}")
        finally:
            await engine.dispose()

        return results

    async def history(self) -> list[dict[str, Any]]:
        """
        Show migration history intelligently.
        Returns a list of dictionaries with revision details,
        highlighting which ones are pending vs applied.
        """

        from alembic.script import ScriptDirectory


        script = ScriptDirectory.from_config(self.config)
        revisions = list(script.walk_revisions())

        # Get head from Alembic logic
        head_rev = script.get_current_head()

        async def fetch_current():
            from sqlalchemy import text
            from sqlalchemy.ext.asyncio import create_async_engine
            from sqlalchemy.pool import NullPool
            url_from_config = self.config.get_main_option("sqlalchemy.url")
            if url_from_config:
                url = url_from_config
            else:
                from eden.config import get_db_url
                url = self.database_url or get_db_url()
            engine = create_async_engine(url, poolclass=NullPool)
            try:
                async with engine.connect() as conn:
                    res = await conn.execute(text("SELECT version_num FROM alembic_version LIMIT 1"))
                    return res.scalar()
            except Exception:
                return None
            finally:
                await engine.dispose()

        current_rev = await fetch_current()

        history_data = []
        # Revisions ordered from head down to base
        # But we want to indicate what has been applied vs what is pending.
        # Anything that we see before seeing the current_rev is pending.
        is_pending = True
        if current_rev is None:
            is_pending = True

        for rev in revisions:
            if rev.revision == current_rev:
                is_pending = False

            history_data.append({
                "revision": rev.revision,
                "message": rev.doc,
                "status": "pending" if is_pending else "applied",
                "is_head": rev.revision == head_rev,
                "is_current": rev.revision == current_rev,
            })

        return history_data


    async def migrate_tenants(
        self, 
        revision: str = "head", 
        continue_on_error: bool = True
    ) -> dict[str, str]:
        """
        Apply pending migrations to ALL active tenant schemas.
        
        Args:
            revision: Target revision (default: "head").
            continue_on_error: If True, continues migrating remaining tenants 
                after one fails. If False, stops at first failure.
        
        Returns:
            Dict mapping schema_name -> status ("ok" or error message).
            
        Raises:
            MigrationError: If continue_on_error=False and a tenant fails.
        """
        from sqlalchemy import select
        from sqlalchemy.ext.asyncio import create_async_engine
        from sqlalchemy.pool import NullPool
        from eden.tenancy.models import Tenant

        logger.info("Migrations: Starting batch tenant migration...")

        # Get database URL reliably
        url = self.config.get_main_option("sqlalchemy.url")
        if not url:
            from eden.config import get_config
            url = get_config().get_database_url()

        engine = create_async_engine(url, poolclass=NullPool)
        results: dict[str, str] = {}
        
        try:
            async with engine.connect() as conn:
                # 1. Fetch all active tenants with schemas
                result = await conn.execute(select(Tenant.schema_name, Tenant.name).where(
                    Tenant.schema_name.isnot(None),
                    Tenant.is_active.is_(True)
                ))
                tenants = result.all()
                
                if not tenants:
                    logger.info("Migrations: No active tenants with schemas found.")
                    return results

                logger.info("Migrations: Found %d tenant(s) to migrate.", len(tenants))

                # 2. Iterate and migrate each one sequentially
                for tenant in tenants:
                    schema_name = tenant.schema_name
                    tenant_name = tenant.name
                    logger.info(
                        "Migrations: Migrating schema '%s' (Tenant: %s)...", 
                        schema_name, tenant_name
                    )
                    try:
                        await self.migrate(revision=revision, schema=schema_name)
                        results[schema_name] = "ok"
                        logger.info(
                            "Migrations: Schema '%s' migrated successfully.", 
                            schema_name
                        )
                    except Exception as e:
                        error_msg = str(e)
                        results[schema_name] = f"error: {error_msg}"
                        logger.error(
                            "Migrations: Failed for tenant '%s' (schema: %s): %s", 
                            tenant_name, schema_name, error_msg
                        )
                        if not continue_on_error:
                            raise MigrationError(
                                f"Tenant migration aborted at schema '{schema_name}': {error_msg}"
                            ) from e
        finally:
            await engine.dispose()

        # 3. Log summary
        succeeded = sum(1 for v in results.values() if v == "ok")
        failed = sum(1 for v in results.values() if v.startswith("error"))
        total = len(results)
        
        if failed:
            logger.warning(
                "Migrations: Batch tenant migration complete. %d/%d succeeded, %d failed.",
                succeeded, total, failed
            )
            for schema, status in results.items():
                if status != "ok":
                    logger.warning("  - %s: %s", schema, status)
        else:
            logger.info(
                "Migrations: Batch tenant migration complete. All %d tenant(s) migrated successfully.",
                total
            )
        
        return results


# ── Functional Interface ──────────────────────────────────────────────────

def init_migrations(db_url: str | None = None):
    import asyncio
    manager = MigrationManager(db_url)
    asyncio.run(manager.init())


def create_migration(message: str, db_url: str | None = None, tenant_isolated: bool = False):
    import asyncio
    manager = MigrationManager(db_url)
    asyncio.run(manager.generate(message, tenant_isolated=tenant_isolated))


def run_upgrade(revision: str, db_url: str | None = None, schema: str | None = None, all_tenants: bool = False):
    import asyncio
    manager = MigrationManager(db_url)
    if all_tenants:
        asyncio.run(manager.migrate_tenants(revision=revision))
    else:
        asyncio.run(manager.migrate(revision, schema=schema))


def run_downgrade(revision: str, db_url: str | None = None, schema: str | None = None):
    import asyncio
    manager = MigrationManager(db_url)
    asyncio.run(manager.downgrade(revision, schema=schema))


def show_history(db_url: str | None = None):
    import asyncio
    manager = MigrationManager(db_url)
    return asyncio.run(manager.history())


def run_check(db_url: str | None = None) -> dict[str, str]:
    import asyncio
    manager = MigrationManager(db_url)
    return asyncio.run(manager.check())
