"""
Eden CLI - Database Migrations

Provides commands for managing database schema changes using Alembic.

Usage:
    eden makemigrations --message "Add new table"
    eden migrate
    eden migrate --down
"""

import asyncio
import os
from typing import Optional
from pathlib import Path
import subprocess
import sys


class MigrationManager:
    """
    Manages database migrations using Alembic.
    Provides easy commands for generating and applying migrations.
    """
    
    def __init__(self, migrations_dir: str = "migrations"):
        """
        Initialize migration manager.
        
        Args:
            migrations_dir: Directory where migrations are stored
        """
        self.migrations_dir = Path(migrations_dir)
    
    async def init_migrations(self) -> None:
        """Initialize migrations directory for a new project."""
        if self.migrations_dir.exists():
            print(f"✓ Migrations directory '{self.migrations_dir}' already exists")
            return
        
        self.migrations_dir.mkdir(parents=True, exist_ok=True)
        
        # Create alembic.ini if it doesn't exist
        alembic_ini = Path("alembic.ini")
        if not alembic_ini.exists():
            await self._create_alembic_ini()
        
        print(f"✓ Initialized migrations at '{self.migrations_dir}'")
    
    async def _create_alembic_ini(self) -> None:
        """Create default alembic.ini configuration."""
        config = """# Alembic Configuration File
# Generated by Eden

[alembic]
# path to migration scripts
script_location = migrations

# template used to generate migration file names
file_template = %%(rev)s_%%(slug)s

[sqlalchemy]
# Use DatabaseURL from environment or config
sqlalchemy.url = driver://user:pass@localhost/dbname

[loggers]
keys = sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %%(levelname)-5.5s [%%(name)s] %%(message)s
datefmt = %H:%M:%S
"""
        with open("alembic.ini", "w") as f:
            f.write(config)
    
    async def make_migrations(
        self,
        message: Optional[str] = None,
        autogenerate: bool = True,
    ) -> None:
        """
        Auto-detect model changes and create migration file.
        
        Args:
            message: Migration message describing changes
            autogenerate: Auto-detect schema changes
        """
        try:
            await self.init_migrations()
            
            # Build alembic command
            cmd = ["alembic", "revision"]
            
            if autogenerate:
                cmd.append("--autogenerate")
            
            if message:
                cmd.extend(["-m", message])
            else:
                cmd.extend(["-m", "Auto migration"])
            
            # Run alembic command
            result = subprocess.run(cmd, capture_output=True, text=True)
            
            if result.returncode == 0:
                print("✓ Migration created successfully")
                if result.stdout:
                    print(result.stdout)
            else:
                print(f"✗ Migration creation failed:")
                print(result.stderr)
                sys.exit(1)
        
        except FileNotFoundError:
            print("✗ Alembic not found. Install with: pip install alembic")
            sys.exit(1)
        except Exception as e:
            print(f"✗ Error creating migration: {e}")
            sys.exit(1)
    
    async def migrate(self, revision: str = "head") -> None:
        """
        Apply pending migrations to database.
        
        Args:
            revision: Target revision (default 'head' = latest)
        """
        try:
            cmd = ["alembic", "upgrade", revision]
            result = subprocess.run(cmd, capture_output=True, text=True)
            
            if result.returncode == 0:
                print("✓ Database migrated successfully")
                if result.stdout:
                    print(result.stdout)
            else:
                print(f"✗ Migration failed:")
                print(result.stderr)
                sys.exit(1)
        
        except FileNotFoundError:
            print("✗ Alembic not found. Install with: pip install alembic")
            sys.exit(1)
        except Exception as e:
            print(f"✗ Error applying migrations: {e}")
            sys.exit(1)
    
    async def downgrade(self, revision: str = "-1") -> None:
        """
        Rollback migrations.
        
        Args:
            revision: Target revision to downgrade to
        """
        try:
            cmd = ["alembic", "downgrade", revision]
            result = subprocess.run(cmd, capture_output=True, text=True)
            
            if result.returncode == 0:
                print("✓ Migration rollback successful")
                if result.stdout:
                    print(result.stdout)
            else:
                print(f"✗ Rollback failed:")
                print(result.stderr)
                sys.exit(1)
        
        except FileNotFoundError:
            print("✗ Alembic not found. Install with: pip install alembic")
            sys.exit(1)
        except Exception as e:
            print(f"✗ Error rolling back migrations: {e}")
            sys.exit(1)
    
    async def current(self) -> None:
        """Show current migration version."""
        try:
            cmd = ["alembic", "current", "-v"]
            result = subprocess.run(cmd, capture_output=True, text=True)
            
            if result.returncode == 0:
                print(result.stdout)
            else:
                print("✗ Error getting current version")
                print(result.stderr)
        
        except FileNotFoundError:
            print("✗ Alembic not found")
        except Exception as e:
            print(f"✗ Error: {e}")
    
    async def history(self) -> None:
        """Show migration history."""
        try:
            cmd = ["alembic", "history"]
            result = subprocess.run(cmd, capture_output=True, text=True)
            
            if result.returncode == 0:
                print(result.stdout)
            else:
                print("✗ Error getting migration history")
                print(result.stderr)
        
        except FileNotFoundError:
            print("✗ Alembic not found")
        except Exception as e:
            print(f"✗ Error: {e}")


# CLI Interface
async def cli_makemigrations(message: Optional[str] = None) -> None:
    """CLI: Create a new migration."""
    manager = MigrationManager()
    await manager.make_migrations(message=message)


async def cli_migrate() -> None:
    """CLI: Apply migrations."""
    manager = MigrationManager()
    await manager.migrate()


async def cli_downgrade() -> None:
    """CLI: Rollback migrations."""
    manager = MigrationManager()
    await manager.downgrade()


async def cli_migration_history() -> None:
    """CLI: Show migration history."""
    manager = MigrationManager()
    await manager.history()
