"""
Eden CLI — New Project Generator

Interactive project scaffolding with rich UI.
"""

import os
import sys
import secrets
import json
from pathlib import Path
from typing import List, Optional

import click
import questionary
from rich.console import Console
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn
from rich.theme import Theme

import eden

def get_extra_packages(extras: List[str]) -> List[str]:
    """Map selected features to their required PyPI packages."""
    packages = []
    if "Payments (Stripe)" in extras:
        packages.append("stripe")
    if "Chats/Websockets" in extras:
        packages.append("websockets")
    if "Mail Support" in extras:
        packages.append("aiosmtplib")
    return packages

# Custom theme for Eden
eden_theme = Theme({
    "info": "cyan",
    "warning": "yellow",
    "error": "red bold",
    "success": "green bold",
    "eden": "green italic",
})

console = Console(theme=eden_theme)

def welcome_banner():
    """Display an attractive welcome banner."""
    console.print(Panel.fit(
        "[eden]🌿 Eden Framework[/eden]\n"
        "[white]Batteries-included async Python web framework[/white]",
        border_style="green",
        padding=(1, 2)
    ))

def generate_minimal(project_dir: Path, name: str, db_type: str, extras: List[str], verbose: bool = False):
    """Generate a single-file minimal project."""
    if verbose:
        console.print(f"  [info]Creating minimal project at: {project_dir}[/info]")
    db_config = get_db_config(db_type, name)
    
    main_content = f'''"""
{name} - Minimal Eden Project 🌿
Generated by Eden CLI
"""

from eden import Eden, Response, html
import os

# 1. Initialize App
app = Eden(
    title="{name}",
    debug=True,
    secret_key=os.getenv("SECRET_KEY", "{secrets.token_hex(32)}")
)

# 2. Database Configuration
app.state.database_url = os.getenv("DATABASE_URL", "{db_config['url']}")

# 3. Middleware (Auto-activated by default in Eden)
# app.add_middleware("security")
# app.add_middleware("session", secret_key=app.secret_key)
# app.add_middleware("cors", allow_origins=["*"])
# app.add_middleware("rate_limit", default_limit="60/minute")
'''

    if "Payments (Stripe)" in extras:
        main_content += '\n# Payments Support\napp.add_middleware("payments", provider="stripe", api_key=os.getenv("STRIPE_KEY"))\n'
    
    if "Chats/Websockets" in extras:
        main_content += '\n# WebSocket Configuration\nfrom eden import WebSocketRouter\nws_router = WebSocketRouter()\n\n@ws_router.on("connect")\nasync def on_connect(socket, user):\n    await socket.accept()\n    await socket.send_json({{"msg": "Connected to {name}"}})\n\napp.include_router(ws_router)\n'

    if "Admin UI" not in extras:
        main_content += '\n# Disable Admin Panel\napp.admin_enabled = False\n'

    main_content += f'''
@app.get("/")
async def index():
    return html("<h1>Welcome to {name} 🌿</h1><p>Minimal setup is ready. Visit <a href='/admin'>/admin</a> to manage your data.</p>")

if __name__ == "__main__":
    app.run()
'''
    (project_dir / "main.py").write_text(main_content, encoding="utf-8")
    (project_dir / ".env").write_text(f"SECRET_KEY={secrets.token_hex(32)}\nDATABASE_URL={db_config['url']}\n", encoding="utf-8")
    
    packages = ["eden-framework", db_config['driver']] + get_extra_packages(extras)
    (project_dir / "requirements.txt").write_text("\n".join(packages) + "\n", encoding="utf-8")

def generate_complete(project_dir: Path, name: str, db_type: str, extras: List[str], verbose: bool = False):
    """Generate a modular complete project structure."""
    if verbose:
        console.print(f"  [info]Creating complete project at: {project_dir}[/info]")
    db_config = get_db_config(db_type, name)
    
    # Create directories
    (project_dir / "app").mkdir()
    (project_dir / "app" / "models").mkdir()
    (project_dir / "app" / "routes").mkdir()
    (project_dir / "app" / "templates").mkdir()
    (project_dir / "static").mkdir()

    # main.py
    main_py = f'''"""
{name} - Main Entry Point 🌿
"""
import uvicorn
from app import create_app

app = create_app()

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="127.0.0.1", port=8123, reload=True)
'''
    (project_dir / "main.py").write_text(main_py, encoding="utf-8")

    # app/__init__.py
    app_init = f'''from eden import Eden
import os
from .routes import main_router

def create_app():
    app = Eden(
        title="{name}",
        secret_key=os.getenv("SECRET_KEY", "{secrets.token_hex(32)}")
    )
    
    app.state.database_url = os.getenv("DATABASE_URL", "{db_config['url']}")
    
    # Core middleware is registered automatically by Eden()
'''

    if "Authentication & RBAC" in extras:
        app_init += '''    # Auth and Authorization are core-integrated in Eden,
    # but you can customize them here if needed.
'''

    if "Payments (Stripe)" in extras:
        app_init += '    app.add_middleware("payments", provider="stripe", api_key=os.getenv("STRIPE_KEY"))\n'

    if "Chats/Websockets" in extras:
        ws_block = f'''    from eden import WebSocketRouter
    ws_router = WebSocketRouter()

    @ws_router.on("connect")
    async def on_connect(socket, user):
        await socket.accept()
        await socket.send_json({{"msg": "Connected to {name}"}})

    app.include_router(ws_router)
'''
        app_init += ws_block

    if "Admin UI" not in extras:
        app_init += '    app.admin_enabled = False\n'

    if "Mail Support" in extras:
        app_init += '    # TODO: configure mail support (e.g. using aiosmtplib)\n'


    app_init += '''    
    # Routes
    app.include_router(main_router)
    
    return app
'''
    (project_dir / "app" / "__init__.py").write_text(app_init, encoding="utf-8")

    # app/routes/__init__.py
    routes_init = '''from eden import Router, html

main_router = Router()

@main_router.get("/")
async def home():
    return html("<h1>Welcome to Eden Complete Setup 🌿</h1><p>Visit <a href='/admin'>/admin</a> to see the auto-generated admin panel.</p>")
'''
    (project_dir / "app" / "routes" / "__init__.py").write_text(routes_init, encoding="utf-8")

    # Setup individual route files if needed
    (project_dir / "app" / "routes" / "api.py").write_text("from eden import Router\n\napi_router = Router()\n", encoding="utf-8")

    # app/models/__init__.py
    models_init = '''from eden.db import Model, StringField

# 🚀 ANY MODEL DEFINED HERE OR IN ANY models.py FILE 
# WILL BE AUTOMATICALLY DISCOVERED BY THE ADMIN UI
# AT THE /admin ENDPOINT.

class Item(Model):
    """An example model that will automatically show up in the Admin Panel."""
    name: str = StringField(max_length=100)
    description: str = StringField(required=False)
'''
    (project_dir / "app" / "models" / "__init__.py").write_text(models_init, encoding="utf-8")

    # .env
    (project_dir / ".env").write_text(f"SECRET_KEY={secrets.token_hex(32)}\nDATABASE_URL={db_config['url']}\n", encoding="utf-8")
    
    # requirements.txt
    packages = ["eden-framework", db_config['driver']] + get_extra_packages(extras)
    (project_dir / "requirements.txt").write_text("\n".join(packages) + "\n", encoding="utf-8")

def get_db_config(db_type: str, project_name: str) -> dict:
    if db_type == "Postgres":
        return {
            "url": f"postgresql+asyncpg://user:pass@localhost:5432/{project_name}",
            "driver": "asyncpg"
        }
    return {
        "url": "sqlite+aiosqlite:///db.sqlite3",
        "driver": "aiosqlite"
    }

def generate_flat(project_dir: Path, name: str):
    """Generate a flat project structure (as expected by tests)."""
    (project_dir / "routes").mkdir(parents=True, exist_ok=True)
    (project_dir / "tests").mkdir(parents=True, exist_ok=True)
    
    (project_dir / "app.py").write_text(f'from eden import Eden\napp = Eden(title="{name}")\n', encoding="utf-8")
    (project_dir / "models.py").write_text('from eden.db import Model\n', encoding="utf-8")
    (project_dir / "settings.py").write_text('DEBUG = True\n', encoding="utf-8")
    (project_dir / "routes" / "__init__.py").write_text('from eden import Router\nmain_router = Router()\n', encoding="utf-8")
    (project_dir / "Dockerfile").write_text('FROM python:3.11\nCMD ["uvicorn", "app:app"]\n', encoding="utf-8")
    (project_dir / "docker-compose.yml").write_text('version: "3.8"\nservices:\n  web:\n    build: .\n', encoding="utf-8")
    (project_dir / "tests" / "conftest.py").write_text('import pytest\n', encoding="utf-8")
    
    (project_dir / "eden.json").write_text(json.dumps({
        "name": name,
        "version": "1.0.0",
        "scale": "flat"
    }, indent=2))

def create_new_project(project_name: str, target_path: Optional[Path] = None, **kwargs):
    """Run the interactive wizard or direct scaffolding."""
    verbose = kwargs.get("verbose", False)
    if target_path:
        # Direct scaffolding (non-interactive, used by tests)
        if not target_path.exists():
            target_path.mkdir(parents=True)
        generate_flat(target_path, project_name)
        console.print(f"[success]✨ Project '{project_name}' scaffolded at {target_path}[/success]")
        return

    welcome_banner()
    
    # Check if directory exists
    target_path = Path.cwd() / project_name
    if target_path.exists():
        console.print(f"[error]Error: Directory '{project_name}' already exists.[/error]")
        return

    # Questions
    db_type = questionary.select(
        "Which database would you like to use?",
        choices=["SQLite", "Postgres"],
        default="SQLite"
    ).ask()

    scale = questionary.select(
        "How do you want to start?",
        choices=["Minimal (One file)", "Complete (Modular)"],
        default="Minimal (One file)"
    ).ask()

    # Extras
    extras = questionary.checkbox(
        "Select additional features to include:",
        choices=[
            questionary.Choice("Admin UI", checked=True),
            questionary.Choice("Authentication & RBAC", checked=True),
            "Payments (Stripe)",
            "Chats/Websockets",
            "Mail Support"
        ]
    ).ask()

    # Summary
    console.print("\n[info]Summary of your new project:[/info]")
    console.print(f"  Name: [cyan]{project_name}[/cyan]")
    console.print(f"  DB:   [cyan]{db_type}[/cyan]")
    console.print(f"  Scale: [cyan]{scale}[/cyan]")
    console.print(f"  Extras: [cyan]{', '.join(extras) if extras else 'None'}[/cyan]\n")

    if not questionary.confirm("Generate project now?").ask():
        console.print("[yellow]Cancelled.[/yellow]")
        return

    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        transient=True,
    ) as progress:
        progress.add_task(description=f"Scaffolding {project_name}...", total=None)
        
        target_path.mkdir(parents=True)
        
        if scale.startswith("Minimal"):
            generate_minimal(target_path, project_name, db_type, extras, verbose=kwargs.get("verbose", False))
        else:
            generate_complete(target_path, project_name, db_type, extras, verbose=kwargs.get("verbose", False))
            
        # Common files
        (target_path / "eden.json").write_text(json.dumps({
            "name": project_name,
            "version": "1.0.0",
            "db": db_type.lower(),
            "scale": "minimal" if scale.startswith("Minimal") else "complete",
            "features": extras
        }, indent=2))

    console.print(f"\n[success]✨ Project '{project_name}' generated successfully![/success]")
    console.print(f"To get started:")
    console.print(f"  [cyan]cd {project_name}[/cyan]")
    console.print(f"  [cyan]pip install -r requirements.txt  # (or use uv pip install)[/cyan]")
    console.print(f"  [cyan]eden run[/cyan]\n")

@click.command()
@click.argument("name")
@click.argument("path", required=False)
@click.option("--verbose", is_flag=True, help="Show detailed generation logs.")
def new(name: str, path: Optional[str] = None, verbose: bool = False):
    """Create a new Eden project interactively."""
    target_path = Path(path) if path is not None else None
    create_new_project(name, target_path, verbose=verbose)
