"""initial

Revision ID: d2d3b0a786fd
Revises: None
Create Date: 2026-03-16 17:25:24.374059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2d3b0a786fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eden_payment_events',
    sa.Column('provider_event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eden_payment_events_event_type'), 'eden_payment_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_eden_payment_events_provider_event_id'), 'eden_payment_events', ['provider_event_id'], unique=True)
    op.create_table('eden_tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=True),
    sa.Column('schema_name', sa.String(length=63), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eden_tenants_slug'), 'eden_tenants', ['slug'], unique=True)
    op.create_table('eden_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.String(), nullable=True),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eden_users_email'), 'eden_users', ['email'], unique=True)
    op.create_index(op.f('ix_eden_users_stripe_customer_id'), 'eden_users', ['stripe_customer_id'], unique=False)
    op.create_table('file_references',
    sa.Column('model_class_name', sa.String(length=255), nullable=False),
    sa.Column('model_instance_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.String(length=2048), nullable=False),
    sa.Column('storage_backend', sa.String(length=50), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_references_model_class_name'), 'file_references', ['model_class_name'], unique=False)
    op.create_index(op.f('ix_file_references_model_instance_id'), 'file_references', ['model_instance_id'], unique=False)
    op.create_table('eden_api_keys',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('prefix', sa.String(length=8), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['eden_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eden_api_keys_key_hash'), 'eden_api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_eden_api_keys_prefix'), 'eden_api_keys', ['prefix'], unique=False)
    op.create_table('eden_customers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_customer_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['eden_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_eden_customers_provider_customer_id'), 'eden_customers', ['provider_customer_id'], unique=True)
    op.create_table('eden_social_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('provider_metadata', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['eden_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eden_social_accounts_provider_user_id'), 'eden_social_accounts', ['provider_user_id'], unique=False)
    op.create_index(op.f('ix_eden_social_accounts_user_id'), 'eden_social_accounts', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['eden_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_table('eden_subscriptions',
    sa.Column('customer_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('provider_subscription_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('price_id', sa.String(length=255), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['eden_customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eden_subscriptions_customer_id'), 'eden_subscriptions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_eden_subscriptions_provider_subscription_id'), 'eden_subscriptions', ['provider_subscription_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eden_subscriptions_provider_subscription_id'), table_name='eden_subscriptions')
    op.drop_index(op.f('ix_eden_subscriptions_customer_id'), table_name='eden_subscriptions')
    op.drop_table('eden_subscriptions')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_eden_social_accounts_user_id'), table_name='eden_social_accounts')
    op.drop_index(op.f('ix_eden_social_accounts_provider_user_id'), table_name='eden_social_accounts')
    op.drop_table('eden_social_accounts')
    op.drop_index(op.f('ix_eden_customers_provider_customer_id'), table_name='eden_customers')
    op.drop_table('eden_customers')
    op.drop_index(op.f('ix_eden_api_keys_prefix'), table_name='eden_api_keys')
    op.drop_index(op.f('ix_eden_api_keys_key_hash'), table_name='eden_api_keys')
    op.drop_table('eden_api_keys')
    op.drop_index(op.f('ix_file_references_model_instance_id'), table_name='file_references')
    op.drop_index(op.f('ix_file_references_model_class_name'), table_name='file_references')
    op.drop_table('file_references')
    op.drop_index(op.f('ix_eden_users_stripe_customer_id'), table_name='eden_users')
    op.drop_index(op.f('ix_eden_users_email'), table_name='eden_users')
    op.drop_table('eden_users')
    op.drop_index(op.f('ix_eden_tenants_slug'), table_name='eden_tenants')
    op.drop_table('eden_tenants')
    op.drop_index(op.f('ix_eden_payment_events_provider_event_id'), table_name='eden_payment_events')
    op.drop_index(op.f('ix_eden_payment_events_event_type'), table_name='eden_payment_events')
    op.drop_table('eden_payment_events')
    # ### end Alembic commands ###
